/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Peduli;

import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author cey0
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static String nikPB;
    public static String namePB;
    
    
    public Login() {
        initComponents();
    }
    private boolean login(String nik, String name, String customPath) {
    String filename = customPath + "/" + nik + "_" + name + ".txt";
    File file = new File(filename);
    return file.exists();
}
    
    private boolean register(String nik, String name, String customPath) {
    File directory = new File(customPath);

    // Create the directory if it doesn't exist
    if (!directory.exists()) {
        if (!directory.mkdirs()) {
            System.out.println("Failed to create directory: " + customPath);
            return false;
        }
    }

    String filename = customPath + "/" + nik + "_" + name + ".txt";
    try {
        File file = new File(filename);
        if (file.createNewFile()) {
            return true;
        } else {
            return false;
        }
    } catch (IOException e) {
        e.printStackTrace();
        return false;
    }
    
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NIKTF = new javax.swing.JTextField();
        NamaTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NIKTF.setBackground(new java.awt.Color(223, 211, 195));
        getContentPane().add(NIKTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 520, 30));

        NamaTF.setBackground(new java.awt.Color(223, 211, 195));
        getContentPane().add(NamaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 520, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("/home/cey0/Unduhan/gallery (3)/belum punya akun_.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, 240, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("/home/cey0/Unduhan/gallery (3)/Login.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 600, 70, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/cey0/Unduhan/LOGIN.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/cey0/Unduhan/Rectangle 2 (1).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, -1, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/cey0/Unduhan/Rectangle 1.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 1020, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/cey0/Unduhan/gallery (2)/NAMA LENGKAP.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 210, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/cey0/Unduhan/Rectangle 2 (1).png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon("/home/cey0/Unduhan/gallery (2)/NIK.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 40, 70));

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setIcon(new javax.swing.ImageIcon("/home/cey0/Unduhan/gallery (3)/Rectangle 4.png")); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, 340, 90));

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setIcon(new javax.swing.ImageIcon("/home/cey0/Unduhan/gallery (3)/Rectangle 4.png")); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, 340, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nik = NIKTF.getText();
        String name = NamaTF.getText();
        String customPath = "/home/cey0/Dokumen/Peduli";

        boolean succes = login(nik,name,customPath);
        if (succes) {
        JOptionPane.showMessageDialog(this, "login successful!");
        nikPB = nik;
        namePB = name;
        insert insert = new insert();
        insert.show();
    } else {
        JOptionPane.showMessageDialog(this, "login failed.");
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String nik = NIKTF.getText();
    String name = NamaTF.getText();
    String customPath = "/home/cey0/Dokumen/Peduli"; // Set your custom path here

    boolean success = register(nik, name, customPath);
    if (success) {
        JOptionPane.showMessageDialog(this, "Registration successful!");
    } else {
        JOptionPane.showMessageDialog(this, "Registration failed.");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIKTF;
    private javax.swing.JTextField NamaTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
